### ISSUE TITLE
Get in contact about project 1 (Build a monadic Web stack in Scala and Scala.js)

### ISSUE THREAD

**Issue by irsital** [fptudelft/IN4355-2015#23]
Hi @ludai0106 & @liuyiran13 can you contact me so we can get started with the project?

Regards, Ishan

**Comment by liuyiran13** [comment]
Hi Ishan, sorry for the late message.  Can we meet next session? We have some exams several days later ,so we are pretty busy these days. 

```
 On Wednesday, October 21, 2015 10:57 AM, irsital <notifications@github.com> wrote:
```

 Hi @ludai0106 & @liuyiran13 can you contact me so we can get started with the project?Regards, Ishan —

**Comment by irsital** [comment]
That's alright. 

So see I'll see you both(?) on the session of the 28th of October? 

Can you please confirm so I can plan my week accordingly. Thanks!

**Comment by ludai0106** [comment]
Exactly Ishan! We Will see u on 28th! 😊Thank you.

**Comment by irsital** [comment]
Alright! Good luck with the exam preparation.
