### ISSUE TITLE
Grades

### ISSUE THREAD

**Issue by JoopAue** [fptudelft/IN4355-2015#47]
Dear Teacher/TA's,

Four weeks have passed since the final presentations for Function Programming and I am curious to know whether you have been able to grade our projects.

I look forward to your reply.

Joop

**Comment by JoopAue** [comment]
It has come to my ear that the grades have been submitted to Osiris, but that there are some technical difficulties due to which it takes a bit longer.

**Comment by headinthebox** [comment]
Yup, they use a regular expression for two-factor authentication that rejects my phone number.

> Het telefoonnummer moet echt via een specifiek format geregistreerd staan, anders lukt het niet. Het format is: +31 (spatie) 6 (spatie) nummer.

If you urgently want to know your grade, don't hesitate to ping us.
